import CartaBase from "./CartaBase";

export default function CartaGaldar() {
  const categorias = [
    {
      nombre: "Montaditos Especial",
      items: [
        { nombre: "Queso cabra con cebolla caramelizada", precio: "2,80 €" },
        { nombre: "Queso ahumado con arándano", precio: "2,80 €" },
        { nombre: "Tortilla", precio: "2,80 €" },
        { nombre: "Pollo Kentucky", precio: "2,80 €" },
        { nombre: "Mini hamburguesas", precio: "2,80 €" },
        { nombre: "Fajitas", precio: "2,80 €" },
        { nombre: "Espiral relleno", precio: "2,80 €" },
        { nombre: "Siempre alguno más", precio: "2,80 €" },
      ],
    },
    {
      nombre: "Montaditos Royer",
      items: [
        { nombre: "Pollo con barbacoa", precio: "2,80 €" },
        { nombre: "Ternera mechada", precio: "2,80 €" },
        { nombre: "Morcilla con tomate deshidratado", precio: "2,80 €" },
        { nombre: "Albóndigas", precio: "2,80 €" },
        { nombre: "Cazón en adobo y mojo", precio: "2,80 €" },
        { nombre: "Solomillo de pollo y huevo", precio: "2,80 €" },
        { nombre: "Chistorras, papas y huevo", precio: "2,80 €" },
        { nombre: "Costilla prensada", precio: "2,80 €" },
        { nombre: "Rabas de calamar", precio: "2,80 €" },
        { nombre: "Filete de merluza", precio: "2,80 €" },
        { nombre: "Atún con pimiento y anchoas", precio: "2,80 €" },
        { nombre: "Chatka y gambas", precio: "2,80 €" },
        { nombre: "Serrano con queso azul y tumaca", precio: "2,80 €" },
        { nombre: "Croquetas", precio: "2,80 €" },
        { nombre: "Jamón york con puerro y queso", precio: "2,80 €" },
        { nombre: "Berros con queso y miel", precio: "2,80 €" },
        { nombre: "Pollo guacamole", precio: "2,80 €" },
        { nombre: "Perritos calientes", precio: "2,80 €" },
        { nombre: "Siempre alguno más", precio: "2,80 €" },
      ],
    },
    {
      nombre: "Para picar / Campo y mar",
      items: [
        { nombre: "Ensalada de cangrejo", precio: "8,95 €" },
        { nombre: "Tomates aliñados con ventresca", precio: "11,80 €" },
        { nombre: "Tabla de queso variado canario", precio: "8,65 €" },
        { nombre: "Papas Antequera", precio: "6,50 €" },
        { nombre: "Chorizo campo", precio: "7,80 €" },
        { nombre: "Jamón ibérico", precio: "16,95 €" },
        { nombre: "Costillas barbacoa", precio: "19,85 €" },
        { nombre: "Codillo en su jugo", precio: "19,85 €" },
        { nombre: "Anchoas", precio: "8,85 €" },
        { nombre: "Boquerones", precio: "8,85 €" },
        { nombre: "Mejillones (18/25 piezas)", precio: "15,95 €" },
        { nombre: "Berberechos", precio: "11,95 €" },
        { nombre: "Langostinos a la carmelita", precio: "14,50 €" },
        { nombre: "Chistorras de Navarra", precio: "7,80 €" },
        { nombre: "Rabas", precio: "8,95 €" },
        { nombre: "Ensalada de pollo mostaza y miel", precio: "8,95 €" },
        { nombre: "Cazuela de albóndigas", precio: "7,20 €" },
        { nombre: "Atún con mojo", precio: "7,85 €" },
        { nombre: "Pulpo a la gallega", precio: "15,50 €" },
        { nombre: "Ensalada de pollo crujiente", precio: "9,85 €" },
        { nombre: "Ensalada cóctel", precio: "10,95 €" },
      ],
    },
    {
      nombre: "Pinchos y banderillas",
      items: [
        { nombre: "Cecina y queso", precio: "1,90 €" },
        { nombre: "Salmón y queso", precio: "2,00 €" },
        { nombre: "Piparra y anchoa", precio: "1,90 €" },
        { nombre: "Boquerón con pimiento", precio: "1,90 €" },
        { nombre: "Queso con anchoas", precio: "1,90 €" },
        { nombre: "Huevo con boquerón", precio: "1,90 €" },
        { nombre: "Boquerón y anchoa (matrimonio)", precio: "1,90 €" },
        { nombre: "Dátil con queso", precio: "1,90 €" },
      ],
    },
    {
      nombre: "Refrescos",
      items: [
        { nombre: "Coca Cola", precio: "2,10 €" },
        { nombre: "Fanta naranja", precio: "2,10 €" },
        { nombre: "Fanta limón", precio: "2,10 €" },
        { nombre: "Nestea", precio: "2,20 €" },
        { nombre: "Zumo bote", precio: "1,70 €" },
        { nombre: "Tónica normal (Schweppes, Nordic M.)", precio: "2,10 €" },
        { nombre: "Tónica especial (Royal Bliss)", precio: "2,10 €" },
        { nombre: "Tónica premium", precio: "2,90 €" },
        { nombre: "Agua con gas", precio: "1,30 €" },
        { nombre: "Agua sin gas", precio: "1,30 €" },
        { nombre: "Bebida energética", precio: "2,80 €" },
        { nombre: "Clipper fresa", precio: "2,10 €" },
        { nombre: "Aquarius", precio: "2,20 €" },
        { nombre: "Appletiser", precio: "2,20 €" },
      ],
    },
    {
      nombre: "Cervezas",
      items: [
        { nombre: "Jarra", precio: "3,50 €" },
        { nombre: "Caña", precio: "1,90 €" },
        { nombre: "Copa de cerveza", precio: "2,30 €" },
        { nombre: "Alhambra 1925", precio: "2,70 €" },
        { nombre: "Alhambra roja", precio: "3,00 €" },
        { nombre: "Alhambra sin alcohol", precio: "2,20 €" },
        { nombre: "Alhambra Radler limón", precio: "2,50 €" },
        { nombre: "Alhambra IPA", precio: "3,90 €" },
        { nombre: "Mahou Radler", precio: "2,50 €" },
        { nombre: "Mahou sin gluten", precio: "2,60 €" },
        { nombre: "Mahou tostada", precio: "2,60 €" },
        { nombre: "Mahou maestra", precio: "2,90 €" },
        { nombre: "Dorada especial", precio: "2,50 €" },
        { nombre: "Dorada sin alcohol", precio: "2,10 €" },
        { nombre: "Dorada sin alcohol limón", precio: "2,20 €" },
        { nombre: "Tropical limón", precio: "2,30 €" },
        { nombre: "San Miguel limón 0.0", precio: "2,60 €" },
      ],
    },
    {
      nombre: "Vino blanco",
      items: [
        { nombre: "Copa afrutado", precio: "3,50 €" },
        { nombre: "Copa Verdejo Castillo de Aza D.O. Rueda", precio: "3,20 €" },
        { nombre: "Copa semi Jaume Serra D.O. Penedès", precio: "3,20 €" },
        { nombre: "Copa manzanilla fino", precio: "2,90 €" },
        { nombre: "Botella afrutado", precio: "16,00 €" },
        { nombre: "Botella Verdejo Castillo de Aza D.O. Rueda", precio: "13,80 €" },
        { nombre: "Botella semi Jaume Serra D.O. Penedès", precio: "13,80 €" },
        { nombre: "Botella Albariño", precio: "13,80 €" },
      ],
    },
    {
      nombre: "Vino rosado",
      items: [
        { nombre: "Copa rosado de mi pueblo", precio: "2,90 €" },
        { nombre: "Botella rosado de mi pueblo", precio: "13,50 €" },
      ],
    },
    {
      nombre: "Vino tinto",
      items: [
        { nombre: "Copa de Rioja", precio: "3,50 €" },
        { nombre: "Copa Figuero 4 D.O. Ribera del Duero Roble", precio: "3,50 €" },
        { nombre: "Copa Pagos de Valcerracín Ribera del Duero Roble", precio: "3,50 €" },
        { nombre: "Copa tinto de verano", precio: "4,40 €" },
        { nombre: "Botella Figuero 4 D.O. Ribera del Duero Roble", precio: "17,00 €" },
        { nombre: "Botella Pagos de Valcerracín Ribera del Duero Roble", precio: "16,00 €" },
        { nombre: "Botella Viña Paceta Crianza D.O. Rioja", precio: "16,00 €" },
      ],
    },
    {
      nombre: "Varios",
      items: [
        { nombre: "Jarra sangría", precio: "9,90 €" },
        { nombre: "Cava", precio: "3,50 €" },
        { nombre: "Copa vermouth Izaguirre reserva", precio: "3,40 €" },
        { nombre: "Smirnoff Ice", precio: "2,50 €" },
        { nombre: "Smirnoff", precio: "4,00 €" },
        { nombre: "Moskovskaya", precio: "4,00 €" },
      ],
    },
    {
      nombre: "Ron",
      items: [
        { nombre: "Matusalen añejo", precio: "4,10 €" },
        { nombre: "Matusalen 15 años", precio: "5,50 €" },
        { nombre: "Barceló añejo", precio: "2,80 €" },
        { nombre: "Carta Oro", precio: "2,80 €" },
        { nombre: "Carta Blanca", precio: "2,80 €" },
        { nombre: "Telde", precio: "2,80 €" },
        { nombre: "Cacique 500", precio: "5,95 €" },
        { nombre: "Cacique añejo", precio: "4,95 €" },
        { nombre: "Santa Teresa", precio: "4,05 €" },
        { nombre: "Havana Club 3 años", precio: "3,90 €" },
        { nombre: "Havana Club 7 años", precio: "4,05 €" },
        { nombre: "La Aldea", precio: "2,85 €" },
        { nombre: "Zacapa", precio: "9,70 €" },
        { nombre: "Chupito ron Zacapa", precio: "4,20 €" },
        { nombre: "Chupito ron", precio: "1,80 €" },
      ],
    },
    {
      nombre: "Ginebras",
      items: [
        { nombre: "Master Mille", precio: "5,00 €" },
        { nombre: "Roco Gin", precio: "7,00 €" },
        { nombre: "Nordés", precio: "5,00 €" },
        { nombre: "Gold", precio: "7,00 €" },
        { nombre: "Bombay", precio: "5,00 €" },
        { nombre: "Gordon's London", precio: "4,00 €" },
        { nombre: "Gordon's Pink", precio: "4,00 €" },
        { nombre: "Sheridan's", precio: "4,95 €" },
        { nombre: "Macaronesia", precio: "5,00 €" },
        { nombre: "Macaronesia Brownie", precio: "5,70 €" },
        { nombre: "Beefeater", precio: "4,00 €" },
        { nombre: "Puerto de Indias", precio: "5,00 €" },
        { nombre: "Tanqueray Ten", precio: "5,00 €" },
        { nombre: "Tanqueray Sevilla", precio: "5,00 €" },
        { nombre: "Tanqueray", precio: "6,30 €" },
        { nombre: "Tanqueray 0.0", precio: "5,00 €" },
        { nombre: "Chupito ginebra", precio: "2,00 €" },
      ],
    },
    {
      nombre: "Whisky",
      items: [
        { nombre: "J&B", precio: "2,80 €" },
        { nombre: "Ballantines", precio: "3,30 €" },
        { nombre: "Jack Daniels", precio: "5,45 €" },
        { nombre: "John Haig", precio: "2,80 €" },
        { nombre: "100 Pipers", precio: "2,80 €" },
        { nombre: "Johnnie Walker etiqueta roja", precio: "2,80 €" },
        { nombre: "Johnnie Walker etiqueta negra", precio: "5,60 €" },
        { nombre: "Cardhu", precio: "6,60 €" },
        { nombre: "Chupito whisky normal", precio: "1,90 €" },
        { nombre: "Chupito Johnnie Walker", precio: "1,90 €" },
        { nombre: "Chupito Johnnie Walker etiqueta negra", precio: "2,90 €" },
      ],
    },
    {
      nombre: "Licores",
      items: [
        { nombre: "Frangelico", precio: "4,45 €" },
        { nombre: "Baileys", precio: "4,45 €" },
        { nombre: "Amaretto", precio: "4,45 €" },
        { nombre: "Mojito", precio: "5,95 €" },
        { nombre: "Mojito de frutas", precio: "6,95 €" },
        { nombre: "Licor", precio: "4,40 €" },
        { nombre: "D.J. Reposado", precio: "5,20 €" },
        { nombre: "Chupito licor", precio: "2,00 €" },
      ],
    },
  ];

  return <CartaBase titulo="Carta - Gáldar" categorias={categorias} />;
}